config/routes.rb
Rails.application.routes.draw do
  # Define resourceful routes for pages, but skip the default :show action.
  resources :pages, except: [ :show ]

  # Create a custom route that maps URLs like /pages/contact
  # to the pages#permalink action. This creates the helper
  # pages_permalink_path.
  get "/pages/:permalink", to: "pages#permalink", as: "pages_permalink"

  # Other routes
  root to: "home#index"
  resources :publishers, only: [ :index, :show ]
  resources :books, only: [ :index, :show ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors

  validates :author_name, presence: true, uniqueness: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  has_many :book_authors
  has_many :authors, through: :book_authors

  paginates_per 10

  validates :book_name, :publishing_year, :language_code, :book_average_rating, :book_ratings_count,
            :genre, :gross_sales, :sale_price, :sale_rank, :units_sold, presence: true
  validates :book_name, uniqueness: true
  validates :publishing_year, :book_ratings_count, :sale_rank, :units_sold, numericality: { only_integer: true }
  validates :book_average_rating, numericality: true

  def authored_by_names
    authors.map(&:author_name).join(", ")
  end
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books
  has_many :authors, through: :books

  validates :publisher_name, presence: true, uniqueness: true

  def self.order_by_book_count
    # SELECT count(publishers.id) as book_count, Publishers.*
    # FROM Publishers
    #   LEFT OUTER JOIN books on books.publisher_id = publishers.id
    # GROUP BY publishers.id
    # ORDER BY book_count DESC;
    @publishers = Publisher.select("publishers.*")
                           .left_joins(:books)
                           .select("publishers.*, COUNT(books.id) AS books_count")
                           .group("publishers.id")
                           .order("books_count DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  helper_method :cms_pages

  def cms_pages
    Page.all
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:q].present?
      @books = Book.where("book_name LIKE ?", "%#{params[:q]}%")
                   .includes(:publisher, :authors)
                   .order(Arel.sql("CAST(gross_sales AS REAL) DESC"))
                   .page(params[:page])
    else
      @books = Book.includes(:publisher, :authors)
                   .order(Arel.sql("CAST(gross_sales AS REAL) DESC"))
                   .page(params[:page])
    end
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.includes(:publisher).order("sale_rank")

    @publishers = Publisher.order_by_book_count.includes(:books).all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]
  http_basic_authenticate_with name: "admin", password: "secret", except: [ :permalink, :show ]

  # GET /pages
  def index
    @pages = Page.all
  end

  # GET /pages/:id
  def show
  end

  # GET /pages/:permalink
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
    if @page.nil?
      render file: "#{Rails.root}/public/404.html", status: :not_found
    end
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/:id/edit
  def edit
  end

  # POST /pages
  def create
    @page = Page.new(page_params)
    respond_to do |format|
      if @page.save
        format.html { redirect_to pages_permalink_path(@page.permalink), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/:id
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to pages_permalink_path(@page.permalink), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/:id
  def destroy
    @page.destroy!
    respond_to do |format|
      format.html { redirect_to pages_path, status: :see_other, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_page
      @page = Page.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:title, :content, :permalink)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    if params[:q].present?
      @publishers = Publisher.where("LOWER(publisher_name) LIKE ?", "%#{params[:q].downcase}%")
    else
      @publishers = Publisher.order_by_book_count
    end
  end

  def show
    @publisher = Publisher.find(params[:id])
    if params[:q].present?
      @books = @publisher.books.where("LOWER(book_name) LIKE ?", "%#{params[:q].downcase}%")
    else
      @books = @publisher.books
    end
    @books = @books.includes(:authors).order(Arel.sql("CAST(gross_sales AS REAL) DESC"))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/books/_book.html.erb
<% if show_link %>
<h1 class="title is-2"><%= link_to book.book_name, book %>
  <small class="has-text-white">
    (Published in <%= book.publishing_year %> | <%= book.genre %> | <%= book.language_code %>)
  </small>
</h1>
<% else %>
<h1 class="title is-2"><%= book.book_name %>
  <small class="has-text-white">
    (Published in <%= book.publishing_year %> | <%= book.genre %> | <%= book.language_code %>)
  </small>
</h1>
<% end %>

<p class="mt-5"><strong>Sale Price:</strong> <%= number_to_currency(book.sale_price) %></p>

<p class="mt-5"><strong>Units Sold:</strong> <%= book.units_sold %></p>

<p class="mt-5"><strong>Gross Sales:</strong> <%= number_to_currency(book.gross_sales) %></p>

<p class="mt-5 mb-5"><strong>Authored By: </strong> <%= book.authored_by_names %></p>

<p class="mt-5 mb-5"><strong>Publisher:</strong> <%= link_to book.publisher.publisher_name, book.publisher %></p>

<p>
  <span><strong>Rating:</strong> <%= book.book_average_rating %></span>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <span><strong>Number of Ratings:</strong> <%= book.book_ratings_count %></span>
</p>

<progress class="progress is-primary mt-5" value="<%= book.book_average_rating %>" max="5">
  <%= book.book_average_rating %> out of 5
</progress>
<hr>

app/views/books/index.html.erb
<div class="mb-4"><%= form_with url: books_path, method: :get, local: true do |form| %>
  <%= form.label :q, "Search Books:" %>
  <%= form.text_field :q, placeholder: "Enter a title or keyword..." %>
  <%= form.submit "Search" %>
<% end %>
</div>

<%= render partial: "book", collection: @books, locals: { show_link: true } %>

<%= paginate @books %>

app/views/books/show.html.erb
<% content_for(:title) {@book.book_name} %>

<%= render partial: "book", locals: { book: @book, show_link: true } %>

app/views/common/_footer.html.erb
<footer>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Books", books_path  %></li>
    <li><%= link_to "Publishers", publishers_path %></li>
    <% cms_pages.each do |page| %>
    <li><%= link_to page.title, pages_permalink_path(page.permalink) %></li>
    <% end %>
  </ul>
</footer>

app/views/home/index.html.erb
<% sorted_books = @books.sort_by { |book| book.gross_sales.to_f }.reverse.first(10) %>

<div class="columns">
  <div class="column">
    <h3 class="title is-2">Top 10 Grossing Books</h3>
    <ol class="ml-5">
      <% sorted_books.each do |book| %>
        <li>
          <%= link_to book.book_name, book %>
          <em>
            Gross Sales: <%= number_to_currency(book.gross_sales) %>
          </em>
        </li>
      <% end %>
    </ol>
    <p class="mt-5 ml-5"><%= link_to "💲💲💲Go to the entire list 💸💸💸", books_path %></p>
  </div>

  <div class="column">
    <h3 class="title is-2">Top Grossing Publishers</h3>
    <ol class="ml-5">
      <% sorted_publishers = @publishers.sort_by do |publisher|
           publisher.books.sum { |book| book.gross_sales.to_f }
         end.reverse %>
      <% sorted_publishers.each do |publisher| %>
        <li>
          <%= link_to publisher.publisher_name, publisher %>
          <em>
            Gross Revenue: <%= number_to_currency(publisher.books.sum { |book| book.gross_sales.to_f }) %>
          </em>
        </li>
      <% end %>
    </ol>
    <p class="mt-5 ml-5"><%= link_to "💲💲💲Go to the publishers list 💸💸💸", publishers_path %></p>
  </div>
</div>

<!-- Center the image at the bottom of the page -->
<div class="has-text-centered">
  <%= image_tag "about.png", alt: "ERD", class: "about-image" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Gross Books" %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
  </head>

  <body>
    <section class="section">
      <div class="section">
        <h1 class="title is-1"><%= link_to "Top Grossing Books", root_path %></h1>
        <%= yield %>
      </div>
      <%= render partial: "common/footer" %>
    </section>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.textarea :content %>
  </div>

  <div>
    <%= form.label :permalink, style: "display: block" %>
    <%= form.text_field :permalink %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Title:</strong>
    <%= page.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= page.content %>
  </p>

  <p>
    <strong>Permalink:</strong>
    <%= page.permalink %>
  </p>

</div>

app/views/pages/edit.html.erb
<% content_for :title, "Editing page" %>

<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", pages_permalink_path(@page.permalink)  %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pages" %>

<h1 class="title is-2">Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", pages_permalink_path(page.permalink) %>
    </p>
    <br>
  <% end %>
</div>
<br>

<%= link_to "New page", new_page_path %>

app/views/pages/new.html.erb
<% content_for :title, "New page" %>

<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/permalink.html.erb
<%# app/views/pages/permalink.html.erb %>
<% content_for(:html_title) { @page.title } %>

<h1 class="title is-2"><%= @page.title %></h1>
<p><%= @page.content %></p>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>

app/views/publishers/_publisher.html.erb
<h1 class="title is-2">Publishers</h1>

<% sorted_publishers = @publishers.sort_by { |publisher| -publisher.books.count } %>
<ol class="ml-5">
  <% sorted_publishers.each do |publisher| %>
    <li>
      <%= link_to publisher.publisher_name, publisher %> printed <%= publisher.books.count %> books in the list
    </li>
  <% end %>
</ol>

app/views/publishers/index.html.erb
<div class="mb-4"><%= form_with url: publishers_path, method: :get, local: true do |form| %>
  <%= form.label :q, "Search Publishers:" %>
  <%= form.text_field :q, placeholder: "Enter a title or keyword..." %>
  <%= form.submit "Search" %>
<% end %>
</div>

<%= render partial: "publisher" %>

app/views/publishers/show.html.erb
<div class="mb-4"><%= form_with url: publisher_path(@publisher), method: :get, local: true do |form| %>
  <%= form.label :q, "Search Books:" %>
  <%= form.text_field :q, placeholder: "Enter book title or keyword..." %>
  <%= form.submit "Search" %>
<% end %></div>

<h1 class="title is-2"><%= @publisher.publisher_name %></h1>
<p class="mb-5">
  <em>
    Printed <%= @publisher.books.count %> books on the list from highest to lowest gross sales
  </em>
</p>

<div class="content">
  <ol>
    <% @books.each do |book| %>
      <li>
        <%= link_to book.book_name, book %>
        (<%= number_to_currency(book.gross_sales) %>)
      </li>
    <% end %>
  </ol>
</div>